version: '2.4'
services:

  mpd01:
    image: toy_mpd_docker_alpine:latest
    container_name: mpd01
    restart: unless-stopped
    ports:
      - 6601:6600/tcp  # MPD Client
    networks:
      - deploy_network      
    volumes:
      - ${FOLDER_TARGET}:/var/lib/mpd/music:z  # look .env

  mpd02:
    image: toy_mpd_docker_alpine:latest
    container_name: mpd02
    restart: unless-stopped
    ports:
      - 6602:6600/tcp  # MPD Client
    networks:
      - deploy_network      
    volumes:
      - ${FOLDER_TARGET}:/var/lib/mpd/music:z  # look .env

networks:
  deploy_network:
    driver: bridge